### Get unsecured data

GET http://localhost:8081/v1/api/unsecured
Content-Type: application/json

### Try get secured data

GET http://localhost:8081/v1/api/secured
Content-Type: application/json

### Login by user

POST http://localhost:8081/v1/api/token
Content-Type: application/json

{
  "username" : "user",
  "password" : "100"
}

### Get secured data with token

GET http://localhost:8081/v1/api/secured
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJleHAiOjE3MDQyNjM5NjYsImlhdCI6MTcwNDI2MzM2Nn0.EdUO1bRKzJKHwhxS0SBtdt7zxWCGztkKCGZlRs6atoQ

### Try get admin data by simple user

GET http://localhost:8081/v1/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJleHAiOjE3MDQyNjM5NjYsImlhdCI6MTcwNDI2MzM2Nn0.EdUO1bRKzJKHwhxS0SBtdt7zxWCGztkKCGZlRs6atoQ

### Login by admin

POST http://localhost:8081/v1/api/token
Content-Type: application/json

{
  "username" : "admin",
  "password" : "110"
}

### Try get admin data by simple user

GET http://localhost:8081/v1/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiZXhwIjoxNzA0MjYxMzk2LCJpYXQiOjE3MDQyNjA3OTZ9.hD0mx2L98gzkhzmU5mC4HgM6qs2aZEvP26nnuFhgGBo

### Create new user

POST http://localhost:8081/v1/api/registration
Content-Type: application/json

{
  "username" : "user1",
  "password" : "123",
  "confirmPassword" : "123",
  "email" : "user1@mail.ru"
}

### Get user info (name)

GET http://localhost:8081/v1/api/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMTEiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNzA0MjY0NjI4LCJpYXQiOjE3MDQyNjQwMjh9.0m9c-to5dfaTZhQgMhShayanDrJcVROWxg46oRCYW5s
